# -*- coding: utf-8 -*-
"""Clean Code NFL Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FMQW7uZSJqnYdYezZIcYjvfYTDLxFxM3
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
import statsmodels.formula.api as smf
import patsy
from patsy import dmatrix
from scipy.stats import gaussian_kde, norm
from scipy.stats import norm

path_merged = "/content/drive/MyDrive/NFL Merged Data/merged_nfl_data_1999_2025_TRIM.csv"
df_pbp = pd.read_csv(path_merged)

unique_years = df_pbp["year"].unique()
print("Unique years in the dataset:", unique_years)

year_counts = df_pbp["year"].value_counts().sort_index()
print(year_counts)

"""**FIELD GOALS ONLY (success)**"""

df_field_goal = df_pbp.loc[
    df_pbp["play_type"].astype(str).str.lower().eq("field_goal") &
    df_pbp["field_goal_result"].isin(["made", "missed", "blocked"])
].copy()

# map to 0/1
df_field_goal['field_goal_result'] = (
    df_field_goal['field_goal_result']
      .map({'made':1,'missed':0,'blocked':0})
      .astype(int)
)

df_field_goal["kick_distance"] = pd.to_numeric(df_field_goal.get("kick_distance"), errors="coerce")
df_field_goal["yardline_100"]  = pd.to_numeric(df_field_goal.get("yardline_100"), errors="coerce")
df_field_goal = df_field_goal.dropna(subset=["kick_distance", "yardline_100"]).copy()

print(df_field_goal.columns)
print("\nYardline_100 (LOS) summary:")
print(df_field_goal["yardline_100"].describe())
print("\nKick_distance summary:")
print(df_field_goal["kick_distance"].describe())

"""# **Summary (make probability)**"""

# Overall summary
print("\n=== Overall summary (make prob uses kick_distance) ===")
print(df_field_goal[["kick_distance", "field_goal_result"]].describe().T)

# success by kick distance (what matters for make%)
by_kdist = (
    df_field_goal
      .groupby("kick_distance")["field_goal_result"]
      .agg(count="size", mean="mean")
      .reset_index()
      .sort_values("kick_distance")
)
print("\n=== Summary by kick_distance ===")
print(by_kdist)

# success + mean kick distance by season
by_season = (
    df_field_goal
      .groupby("year")
      .agg(
          mean_kick_distance=("kick_distance", "mean"),
          attempts=("field_goal_result", "size"),
          success_rate=("field_goal_result", "mean")
      )
      .sort_index()
)
print("\n=== Summary by season ===")
print(by_season)

# plot: make% vs kick distance
plt.figure()
plt.plot(by_kdist["kick_distance"], by_kdist["mean"])
plt.xlabel("Kick distance (yards)")
plt.ylabel("Success rate")
plt.title("Field-goal success rate by kick distance")
plt.tight_layout()
plt.show()

# plot: mean kick distance by season
plt.figure()
plt.plot(by_season.index, by_season["mean_kick_distance"])
plt.xlabel("Season")
plt.ylabel("Mean kick distance (yards)")
plt.title("Mean field-goal kick distance by season")
plt.tight_layout()
plt.show()

# plot: mean success rate by season
plt.figure()
plt.plot(by_season.index, by_season["success_rate"])
plt.xlabel("Season")
plt.ylabel("Success rate")
plt.title("Mean field-goal success rate by season")
plt.tight_layout()
plt.show()

"""# **Summary Attempt Behavior**"""

# this is "where teams choose to kick" -> use LOS (yardline_100)
by_los = (
    df_field_goal
      .assign(los_yd=df_field_goal["yardline_100"].round().astype("Int64"))
      .groupby("los_yd")["field_goal_result"]
      .agg(attempts="size", make_rate="mean")
      .reset_index()
      .sort_values("los_yd")
)
print("\n=== Attempt counts by LOS (yardline_100) ===")
print(by_los)

plt.figure()
plt.plot(by_los["los_yd"], by_los["attempts"])
plt.xlabel("Line of scrimmage: yardline_100 (yards to end zone)")
plt.ylabel("FG attempts (count)")
plt.title("Field-goal attempts by LOS (attempt behavior)")
plt.tight_layout()
plt.show()

"""# **ROOKIES ONLY (SUMMARY)**"""

df_field_goal = df_field_goal.copy()

df_field_goal["career_attempts"] = (
    df_field_goal
      .groupby("kicker_player_name", observed=True)["kicker_player_name"]
      .transform("size")
)

kickers = (
    df_field_goal[["kicker_player_name", "career_attempts"]]
      .drop_duplicates()
      .sort_values(["career_attempts", "kicker_player_name"])
      .reset_index(drop=True)
)

kickers["cum_share"] = kickers["career_attempts"].cumsum() / kickers["career_attempts"].sum()

# attempt-share terciles (≈ 1/3 attempts each)

kickers["quality"] = pd.cut(
    kickers["cum_share"],
    bins=[0.0, 1/3, 2/3, 1.0],
    labels=["Rookie", "Mid", "Veteran"],
    include_lowest=True,
    right=True
).astype("category")

df_field_goal["quality"] = df_field_goal["kicker_player_name"].map(
    kickers.set_index("kicker_player_name")["quality"]
).astype("category")

print("\nQuality counts:")
print(df_field_goal["quality"].value_counts())

df_r = df_field_goal.loc[df_field_goal["quality"].eq("Rookie")].copy()
if df_r.empty:
    raise ValueError("No rookie attempts found (quality == 'Rookie').")

# typed
df_r["kick_distance"] = pd.to_numeric(df_r["kick_distance"], errors="coerce")
df_r["field_goal_result"] = pd.to_numeric(df_r["field_goal_result"], errors="coerce")
df_r["season"] = pd.to_numeric(df_r.get("season", df_r.get("year")), errors="coerce")

df_r = df_r.dropna(subset=["field_goal_result", "kick_distance", "season"]).copy()

df_r["dist_yd"] = df_r["kick_distance"].round().astype(int)
df_r_inrange = df_r[(df_r["dist_yd"] >= 20) & (df_r["dist_yd"] <= 50)].copy()

print("\n=== Rookie-only overall summary ===")
print(df_r[["kick_distance", "field_goal_result"]].describe().T)

by_dist_r = (
    df_r_inrange
      .groupby("dist_yd", as_index=False)["field_goal_result"]
      .agg(count="size", mean="mean")
      .rename(columns={"dist_yd": "kick_distance"})
      .sort_values("kick_distance")
)
print("\n=== Rookie-only summary by kick distance (20–50) ===")
print(by_dist_r)

by_season_r = (
    df_r
      .groupby("season")
      .agg(
          mean_kick_distance=("kick_distance", "mean"),
          attempts=("field_goal_result", "size"),
          success_rate=("field_goal_result", "mean")
      )
      .sort_index()
)
print("\n=== Rookie-only summary by season ===")
print(by_season_r)

min_attempts = 10
plot_df = by_dist_r[by_dist_r["count"] >= min_attempts]

plt.figure()
plt.plot(plot_df["kick_distance"], plot_df["mean"])
plt.xlabel("Kick distance (yards)")
plt.ylabel("Success rate")
plt.title("Rookie FG success rate by kick distance (20–50)")
plt.tight_layout()
plt.show()

plt.figure()
plt.plot(by_season_r.index, by_season_r["mean_kick_distance"])
plt.xlabel("Season")
plt.ylabel("Mean kick distance (yards)")
plt.title("Rookie mean kick distance by season")
plt.tight_layout()
plt.show()

plt.figure()
plt.plot(by_season_r.index, by_season_r["success_rate"])
plt.xlabel("Season")
plt.ylabel("Success rate")
plt.title("Rookie FG success rate by season")
plt.tight_layout()
plt.show()

# rookies: attempt behavior by LOS (yardline_100)
by_los_r = (
    df_r
      .assign(los_yd=df_r["yardline_100"].round().astype("Int64"))
      .groupby("los_yd")["field_goal_result"]
      .agg(attempts="size", make_rate="mean")
      .reset_index()
      .sort_values("los_yd")
)
print("\n=== Rookie FG attempts by LOS (yardline_100) ===")
print(by_los_r)

"""## **SUCCESS PROBABILITY (make%) BY KICK DISTANCE**"""

# coerce + round to clean integer yards
df_field_goal["kick_distance"] = pd.to_numeric(df_field_goal.get("kick_distance"), errors="coerce")
df_field_goal = df_field_goal.dropna(subset=["kick_distance", "field_goal_result"]).copy()
df_field_goal["dist_yd"] = df_field_goal["kick_distance"].round().astype(int)

# success by exact kick distance
by_dist = (
    df_field_goal
      .groupby("dist_yd")["field_goal_result"]
      .agg(success_rate="mean", attempts="size")
      .reset_index()
      .sort_values("dist_yd")
)

# drop tiny-sample distances
min_attempts = 20
plot_df = by_dist[by_dist["attempts"] >= min_attempts].copy()

plt.figure()
plt.plot(plot_df["dist_yd"], plot_df["success_rate"])
plt.xlabel("Kick distance (yards)")
plt.ylabel("Make probability")
plt.title("FG make probability by kick distance")
plt.tight_layout()

out_path = "/content/drive/MyDrive/NFL Merged Data/fg_success_by_distance.png"
plt.savefig(out_path, dpi=150)
plt.show()

print(plot_df.head(10))
print("Saved to:", out_path)


# =========================
# ROOKIES ONLY: make% BY KICK DISTANCE
# =========================

df_r = df_field_goal.loc[df_field_goal["quality"].eq("Rookie")].copy()
if df_r.empty:
    raise ValueError("No rookie attempts found (quality == 'Rookie').")

df_r["kick_distance"] = pd.to_numeric(df_r.get("kick_distance"), errors="coerce")
df_r["field_goal_result"] = pd.to_numeric(df_r.get("field_goal_result"), errors="coerce")
df_r = df_r.dropna(subset=["kick_distance", "field_goal_result"]).copy()

df_r["dist_yd"] = df_r["kick_distance"].round().astype(int)

# keep the range you were using
df_r = df_r[(df_r["dist_yd"] >= 20) & (df_r["dist_yd"] <= 50)].copy()

by_dist_r = (
    df_r
      .groupby("dist_yd")["field_goal_result"]
      .agg(success_rate="mean", attempts="size")
      .reset_index()
      .sort_values("dist_yd")
)

min_attempts = 10
plot_df_r = by_dist_r[by_dist_r["attempts"] >= min_attempts].copy()

plt.figure()
plt.plot(plot_df_r["dist_yd"], plot_df_r["success_rate"])
plt.xlim(20, 50)
plt.xlabel("Kick distance (yards)")
plt.ylabel("Make probability")
plt.title("Rookie FG make probability by kick distance (20–50)")
plt.tight_layout()
plt.show()

"""# **DENSITY-JUMP TEST (COUNT-BASED, LOS / yardline_100)**"""

# 1) LOS yardline as integer running variable
df_field_goal = df_field_goal.drop(columns=["yl"], errors="ignore")

df_field_goal["yl"] = (
    pd.to_numeric(df_field_goal["yardline_100"], errors="coerce")
      .round(0)
      .astype("Int64")
)

# keep plausible FG snap spots
df_jump = df_field_goal.dropna(subset=["yl"]).copy()
df_jump = df_jump[(df_jump["yl"] >= 0) & (df_jump["yl"] <= 60)].copy()

print("dtype of df_jump['yl']:", df_jump["yl"].dtype)

# 2) counts by LOS yardline
counts_by_yl = df_jump["yl"].value_counts().sort_index()

# 3) McCrary-style count jump around a cut
def density_jump_test_counts(counts_series, cutpoint, bandwidth=10):
    lower, upper = cutpoint - bandwidth, cutpoint + bandwidth
    dists = np.arange(lower, upper + 1)

    df_cnt = pd.DataFrame({"yl": dists})
    df_cnt["count"] = df_cnt["yl"].map(counts_series).fillna(0).astype(int)
    df_cnt["rp"] = df_cnt["yl"] - cutpoint

    left  = df_cnt[df_cnt["yl"] < cutpoint]
    right = df_cnt[df_cnt["yl"] >= cutpoint]

    Xl = sm.add_constant(left["rp"])
    Xr = sm.add_constant(right["rp"])

    ml = sm.OLS(left["count"], Xl).fit()
    mr = sm.OLS(right["count"], Xr).fit()

    dens_left  = float(ml.params["const"])
    dens_right = float(mr.params["const"])

    jump = dens_right - dens_left
    se = np.sqrt(
        ml.cov_params().loc["const", "const"] +
        mr.cov_params().loc["const", "const"]
    )
    z_val = jump / se if se > 0 else np.nan
    p_val = 2 * (1 - norm.cdf(abs(z_val))) if np.isfinite(z_val) else np.nan

    return {
        "cut": cutpoint,
        "dens_left": dens_left,
        "dens_right": dens_right,
        "jump": jump,
        "se_jump": float(se),
        "z": float(z_val),
        "p_value": float(p_val),
    }

# 4) run cuts on LOS yardline
candidate_cuts = [20, 25, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 45]

results = [density_jump_test_counts(counts_by_yl, c, bandwidth=10) for c in candidate_cuts]

df_density_jumps = pd.DataFrame(results)[
    ["cut", "dens_left", "dens_right", "jump", "se_jump", "z", "p_value"]
]

print("---- Density-jump results (count-based, LOS yardline_100 version) ----")
print(df_density_jumps.to_string(index=False))

"""# **RAW SUCCESS RATE SCATTER + LOWESS (vs kick_distance)**"""

# 0) Kick_distance is numeric
df_field_goal["kick_distance"] = pd.to_numeric(df_field_goal["kick_distance"], errors="coerce")
df_field_goal = df_field_goal.dropna(subset=["kick_distance", "field_goal_result"]).copy()

# 1) group on rounded kick distance (integer yards)
df_field_goal["dist_yd"] = df_field_goal["kick_distance"].round().astype("Int64")

success_by_dist = (
    df_field_goal.groupby("dist_yd")["field_goal_result"]
      .agg(success_rate="mean", attempts="size")
      .reset_index()
      .dropna(subset=["dist_yd"])
      .sort_values("dist_yd")
)

# 2) scatter + lowess
plt.figure(figsize=(10, 4))
plt.scatter(
    success_by_dist["dist_yd"],
    success_by_dist["success_rate"],
    s=success_by_dist["attempts"] * 0.05,
    alpha=0.6,
    label="Raw success (size ∝ attempts)"
)

lowess = sm.nonparametric.lowess(
    success_by_dist["success_rate"],
    success_by_dist["dist_yd"].astype(float),
    frac=0.3
)
plt.plot(lowess[:, 0], lowess[:, 1], color="red", lw=2, label="LOWESS")

plt.axvline(33, color="purple", linestyle="--", alpha=0.6, label="33 yd")
plt.xlabel("Kick distance (yards)")
plt.ylabel("Success probability")
plt.title("Raw FG success rate vs kick distance")
plt.legend()
plt.tight_layout()
plt.show()

"""# **RDD LOOP (LPM + LOGIT) — running variable = kick_distance**"""

cuts = [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 45]

for c in cuts:
    lo, hi = c - 10, c + 10

    d = df_field_goal[(df_field_goal["kick_distance"] >= lo) &
                      (df_field_goal["kick_distance"] <= hi)].copy()
    if d.empty:
        print(f"\nCut {c}: no data in window.")
        continue

    d["above"] = (d["kick_distance"] >= c).astype(int)
    d["run"]   = d["kick_distance"] - c

    # LPM
    X = sm.add_constant(d[["above", "run"]])
    y = d["field_goal_result"].astype(float)

    lpm = sm.OLS(y, X).fit(cov_type="HC1")
    print(f"\nRDD (LPM) at {c} yds — coef on above:")
    print(lpm.summary().tables[1])

    # logit (guard for failures)
    try:
        logit = sm.Logit(y, X).fit(disp=False)
        print(f"\nRDD (Logit) at {c} yds — coef on above:")
        print(logit.summary2().tables[1])
    except Exception as e:
        print(f"Logit failed at cut {c}: {e}")

    print("\n" + "-" * 60)

"""# **KINK** MODELS - hinge in kick_distance"""

# prep controls once
df_field_goal["stadium_open"] = (
    df_field_goal["roof"].fillna("unknown").astype(str).str.lower().eq("open")
).astype(int)

df_field_goal["temp_filled"] = pd.to_numeric(df_field_goal["temp"], errors="coerce")
df_field_goal["temp_filled"] = df_field_goal["temp_filled"].fillna(df_field_goal["temp_filled"].median())

def run_kink(cut, window=10):
    d = df_field_goal[(df_field_goal["kick_distance"] >= cut - window) &
                      (df_field_goal["kick_distance"] <= cut + window)].copy()
    if d.empty:
        print(f"\nKink {cut}: no data in window.")
        return

    d["x_c"] = d["kick_distance"] - cut
    d["below_slope"] = np.where(d["kick_distance"] < cut, d["x_c"], 0)
    d["above_slope"] = np.where(d["kick_distance"] >= cut, d["x_c"], 0)

    # simple
    simple = smf.ols("field_goal_result ~ below_slope + above_slope", data=d).fit()
    print(f"\nSimple kink {cut}:")
    print(f"  below slope = {simple.params['below_slope']:.4f}")
    print(f"  above slope = {simple.params['above_slope']:.4f}")

    # controlled + clustered
    formula = "field_goal_result ~ below_slope + above_slope + stadium_open + temp_filled"

    if "game_id" in d.columns and d["game_id"].notna().any():
        ctl = smf.ols(formula, data=d).fit(cov_type="cluster", cov_kwds={"groups": d["game_id"]})
    else:
        ctl = smf.ols(formula, data=d).fit(cov_type="HC1")

    print(f"Kink {cut} with controls:")
    print(f"  below slope = {ctl.params['below_slope']:.4f} (p={ctl.pvalues['below_slope']:.3f})")
    print(f"  above slope = {ctl.params['above_slope']:.4f} (p={ctl.pvalues['above_slope']:.3f})")
    print("\n" + "-" * 60)

for cut in [33, 34, 35, 36, 37, 38, 39]:
    run_kink(cut, window=10)

"""# **CAETANO DUMMY TESTS (CLUTCH / STADIUM / EXPERIENCE)**"""

# Create 'game_half' column based on 'qtr'
df_field_goal['game_half'] = df_field_goal['qtr'].apply(lambda x: 'First Half' if x <= 2 else ('Second Half' if x <= 4 else 'Overtime'))

# Verify the new column
print(df_field_goal[['qtr', 'game_half']].drop_duplicates())

# Clutch Kicks (Last 2 Minutes or OT)
df_field_goal['clutch_kick'] = ((df_field_goal['game_seconds_remaining'] <= 120) | (df_field_goal['game_half'] == "Overtime")).astype(int)
model_clutch = sm.GLM.from_formula("field_goal_result ~ clutch_kick", family=sm.families.Binomial(), data=df_field_goal)
print(model_clutch.fit().summary())

# Stadium Type (Domed vs Open)

# 0) 0/1 dummy for open vs. domed
df_field_goal['stadium_open'] = (
    df_field_goal['roof']
      .fillna("unknown")
      .eq('open')
).astype(int)

# 1) Binomial GLM on that numeric dummy
import statsmodels.api as sm
model_stadium = sm.GLM.from_formula(
    "field_goal_result ~ stadium_open",
    family=sm.families.Binomial(),
    data=df_field_goal
)
print(model_stadium.fit().summary())

# Kicker Experience
df_field_goal['kicker_experience'] = df_field_goal.groupby('kicker_player_name').cumcount() + 1
model_experience = sm.GLM.from_formula("field_goal_result ~ kicker_experience", family=sm.families.Binomial(), data=df_field_goal)
print(model_experience.fit().summary())

# 0) Numeric stadium dummy
df_field_goal['stadium_open'] = (
    df_field_goal['roof'].fillna("unknown") == 'open'
).astype(int)

# 1) 'stadium_type' and 'clutch_kick'
df_field_goal['stadium_type'] = df_field_goal['roof'].apply(
    lambda x: 'domed' if x in ['dome', 'closed'] else 'open'
)

df_field_goal['clutch_kick'] = (
    (df_field_goal['game_seconds_remaining'] <= 120)
    | (df_field_goal['game_half'] == "Overtime")
).astype(int)

# 2) Wind/temp for domed stadiums:
#    - For wind: 0 (no wind inside a dome)
#    - For temp: 70°F (typical controlled temperature)
df_field_goal['wind_filled'] = df_field_goal['wind']
df_field_goal['temp_filled'] = df_field_goal['temp']

df_field_goal.loc[
    df_field_goal['stadium_type'] == 'domed',
    'wind_filled'
] = 0.0

df_field_goal.loc[
    df_field_goal['stadium_type'] == 'domed',
    'temp_filled'
] = 72.0

# 3) open‐air rows still have missing wind/temp, fill with the overall median:
df_field_goal['wind_filled'] = df_field_goal['wind_filled'].fillna(
    df_field_goal['wind_filled'].median()
)
df_field_goal['temp_filled'] = df_field_goal['temp_filled'].fillna(
    df_field_goal['temp_filled'].median()
)

# 4) Domed rows have no missing wind_filled/temp_filled:
print(
    "Domed wind/temp missing after fill:",
    df_field_goal.loc[df_field_goal['stadium_type']=='domed',
                      ['wind_filled','temp_filled']].isna().sum()
)

# 5) Patsy design matrices *without* C(...)
import patsy, statsmodels.api as sm

formula = (
    "field_goal_result ~ stadium_open"
  + " + kicker_experience + clutch_kick + wind_filled"
  + " + wind_filled + temp_filled"
)

y_all, X_all = patsy.dmatrices(formula,
                               data=df_field_goal,
                               return_type='dataframe')

# 5a) Confirm both stadium types survived:
print(
    "Remaining stadium types in design:",
    df_field_goal.loc[y_all.index, 'stadium_type'].value_counts()
)

# 6) Matching game_id for clustering:
aligned_game_ids = df_field_goal.loc[y_all.index, 'game_id']

# 7)  Clustered logit for correct SEs by game:
model_stadium_fixed = sm.Logit(y_all, X_all).fit(
    cov_type='cluster',
    cov_kwds={'groups': aligned_game_ids}
)

print(model_stadium_fixed.summary())

"""# **Covariate Discontinuity Test**"""

# 0) basic prep
df = df_field_goal.copy()

# stadium type + dummy
roof = df["roof"].fillna("unknown").astype(str).str.lower()
df["stadium_type"] = np.where(roof.eq("open"), "open", "domed")
df["stadium_domed"] = (df["stadium_type"] == "domed").astype(int)

# running variable (team choice) = yardline_100
df["yardline_100"] = pd.to_numeric(df.get("yardline_100"), errors="coerce")
df = df.dropna(subset=["yardline_100", "field_goal_result"]).copy()

# covariates to test
covariates = ["kicker_experience", "wind_filled", "temp_filled", "stadium_domed", "clutch_kick"]
cuts = [20, 25, 30, 31, 33, 34, 35, 37, 38]

# fill missing covariates
if "wind_filled" not in df.columns:
    df["wind_filled"] = pd.to_numeric(df.get("wind"), errors="coerce").fillna(0)
else:
    df["wind_filled"] = pd.to_numeric(df["wind_filled"], errors="coerce").fillna(0)

if "temp_filled" not in df.columns:
    t = pd.to_numeric(df.get("temp"), errors="coerce")
    df["temp_filled"] = t.fillna(t.median())
else:
    t = pd.to_numeric(df["temp_filled"], errors="coerce")
    df["temp_filled"] = t.fillna(t.median())

if "kicker_experience" in df.columns:
    df["kicker_experience"] = pd.to_numeric(df["kicker_experience"], errors="coerce")
else:
    covariates.remove("kicker_experience")

if "clutch_kick" in df.columns:
    df["clutch_kick"] = pd.to_numeric(df["clutch_kick"], errors="coerce").fillna(0).astype(int)
else:
    covariates.remove("clutch_kick")


# 1) covariate discontinuity: z ~ rp + D around each cut
disc_results = []

for c in cuts:
    win = df[(df["yardline_100"] >= c - 10) & (df["yardline_100"] <= c + 10)].copy()
    if win.empty:
        continue

    win["D"] = (win["yardline_100"] >= c).astype(int)
    win["rp"] = win["yardline_100"] - c

    for z in covariates:
        win[z] = pd.to_numeric(win[z], errors="coerce")
        tmp = win.dropna(subset=["rp", "D", z])
        if len(tmp) < 10:
            continue

        m = smf.ols(f"{z} ~ rp + D", data=tmp).fit(cov_type="HC1")
        disc_results.append({
            "cut": c,
            "covariate": z,
            "coef_D": float(m.params.get("D", np.nan)),
            "pval_D": float(m.pvalues.get("D", np.nan)),
            "N": int(len(tmp))
        })

df_disc = pd.DataFrame(disc_results).sort_values(["cut", "covariate"])


# 2) LCDT-style check at each cut (using yardline_100)
lcdt_results = []

for c in cuts:
    s1 = df[df["yardline_100"].round().eq(c)].copy()
    if s1.empty:
        continue

    s1c = s1.dropna(subset=covariates + ["field_goal_result"])
    if len(s1c) < max(10, len(covariates) + 2):
        continue

    Z1 = sm.add_constant(s1c[covariates])
    mod1 = sm.OLS(s1c["field_goal_result"], Z1).fit()

    s2 = df[df["yardline_100"] > c].copy()
    s2c = s2.dropna(subset=covariates + ["field_goal_result"])
    if s2c.empty:
        continue

    Z2 = sm.add_constant(s2c[covariates])
    Q = mod1.predict(Z2) - s2c["field_goal_result"]

    theta = float(Q.mean())
    se = float(Q.std(ddof=1) / np.sqrt(len(Q))) if len(Q) > 1 else np.nan
    t_stat = theta / se if (se is not None and se > 0) else np.nan
    p_val = float(2 * (1 - norm.cdf(abs(t_stat)))) if np.isfinite(t_stat) else np.nan

    lcdt_results.append({
        "cut": c,
        "theta_LCDT": theta,
        "SE": se,
        "t_stat": t_stat,
        "p_value": p_val,
        "N_at_cut": int(len(s1c)),
        "N_above": int(len(s2c))
    })

df_lcdt = pd.DataFrame(lcdt_results).sort_values("cut")


print("Covariate Discontinuity Tests (running var = yardline_100)")
print(df_disc.to_string(index=False))

print("\nLinear CDT Results (running var = yardline_100)")
print(df_lcdt.to_string(index=False))

"""# **Univariate Dummy Test - Dummy + Controls - Interactions**"""

df = df_field_goal.copy()

# 0) types / basics
df["field_goal_result"] = pd.to_numeric(df.get("field_goal_result"), errors="coerce")
df["kick_distance"] = pd.to_numeric(df.get("kick_distance"), errors="coerce")
df["year"] = pd.to_numeric(df.get("year"), errors="coerce")

df = df.dropna(subset=["field_goal_result", "kick_distance"]).copy()
df["dist_yd"] = df["kick_distance"].round().astype(int)

# 1) wind/temp fills (same as earlier)
if "wind_filled" not in df.columns:
    df["wind_filled"] = pd.to_numeric(df.get("wind"), errors="coerce").fillna(0)
else:
    df["wind_filled"] = pd.to_numeric(df["wind_filled"], errors="coerce").fillna(0)

if "temp_filled" not in df.columns:
    t = pd.to_numeric(df.get("temp"), errors="coerce")
    df["temp_filled"] = t.fillna(t.median())
else:
    t = pd.to_numeric(df["temp_filled"], errors="coerce")
    df["temp_filled"] = t.fillna(t.median())

# 2) stadium_type categorical
if "stadium_type" not in df.columns:
    roof = df.get("roof", "unknown").fillna("unknown").astype(str).str.lower()
    df["stadium_type"] = np.where(roof.eq("open"), "open", "domed")
df["stadium_type"] = df["stadium_type"].astype("category")

# 3) clutch + experience (fallbacks if missing)
if "clutch_kick" in df.columns:
    df["clutch_kick"] = pd.to_numeric(df["clutch_kick"], errors="coerce").fillna(0).astype(int)
else:
    df["clutch_kick"] = 0

if "kicker_experience" in df.columns:
    df["kicker_experience"] = pd.to_numeric(df["kicker_experience"], errors="coerce")
else:
    df["kicker_experience"] = np.nan  # keeps formulas stable if you later drop it

# 4) poly terms (avoid I())
df["kd_sq"] = df["kick_distance"] ** 2
df["kd_cu"] = df["kick_distance"] ** 3

# 5) controls string
controls = "kick_distance + kd_sq + kd_cu + wind_filled + temp_filled + stadium_type"

# 6) SE choice
def fit_robust(m, d):
    if "game_id" in d.columns and d["game_id"].notna().any():
        return m.fit(cov_type="cluster", cov_kwds={"groups": d["game_id"]})
    return m.fit(cov_type="HC1")


# --- A) per-cut: dummy, dummy+controls, interactions ---
def run_univariate_models(d, cut):
    out = d.copy()
    dummy = f"D{cut}"
    out[dummy] = (out["dist_yd"] == cut).astype(int)

    print(f"\n=== Dummy only @ {cut}yd (kick_distance) ===")
    m1 = fit_robust(smf.ols(f"field_goal_result ~ {dummy}", data=out), out)
    print(m1.summary().tables[1])

    print(f"\n=== Dummy + controls @ {cut}yd ===")
    m2 = fit_robust(smf.ols(f"field_goal_result ~ {dummy} + {controls}", data=out), out)
    print(m2.summary().tables[1])

    print(f"\n=== Interactions @ {cut}yd ===")
    rhs = (
        f"{dummy} * wind_filled + {dummy} * temp_filled + {dummy} * kick_distance"
        " + kd_sq + kd_cu + stadium_type"
    )
    if "kicker_experience" in out.columns and out["kicker_experience"].notna().any():
        rhs += " + kicker_experience"
    if "clutch_kick" in out.columns:
        rhs += " + clutch_kick"

    m3 = fit_robust(smf.ols(f"field_goal_result ~ {rhs}", data=out), out)
    print(m3.summary().tables[1])


cuts = [20, 25, 30, 31, 32, 33, 34, 35, 36, 37, 38]
for c in cuts:
    run_univariate_models(df, c)


# --- B) pooled dummies + year interactions (kick_distance cutpoints) ---
df2 = df.copy()
df2["yr_c"] = df2["year"] - df2["year"].mean()

for c in cuts:
    df2[f"D{c}"] = (df2["dist_yd"] == c).astype(int)
    df2[f"D{c}_yr"] = df2[f"D{c}"] * df2["yr_c"]

ctrls = "kick_distance + kd_sq + wind_filled + temp_filled + stadium_type"
dummy_terms = " + ".join([f"D{c} + D{c}_yr" for c in cuts])

formula = f"field_goal_result ~ {dummy_terms} + {ctrls}"

m_int = smf.ols(formula, data=df2)
m_int = fit_robust(m_int, df2)

print("\n=== Pooled dummy + year-interaction model ===")
print(m_int.summary().tables[1])

"""# **Pre and Post 2015**"""

# **PRE vs POST 2015 (running var = kick_distance)**

df = df_field_goal.copy()

# 0) types / basics
df["field_goal_result"] = pd.to_numeric(df.get("field_goal_result"), errors="coerce")
df["kick_distance"] = pd.to_numeric(df.get("kick_distance"), errors="coerce")
df["year"] = pd.to_numeric(df.get("year"), errors="coerce")

df = df.dropna(subset=["field_goal_result", "kick_distance", "year"]).copy()
df["dist_yd"] = df["kick_distance"].round().astype(int)

# 1) wind/temp fills
if "wind_filled" not in df.columns:
    df["wind_filled"] = pd.to_numeric(df.get("wind"), errors="coerce").fillna(0)
else:
    df["wind_filled"] = pd.to_numeric(df["wind_filled"], errors="coerce").fillna(0)

if "temp_filled" not in df.columns:
    t = pd.to_numeric(df.get("temp"), errors="coerce")
    df["temp_filled"] = t.fillna(t.median())
else:
    t = pd.to_numeric(df["temp_filled"], errors="coerce")
    df["temp_filled"] = t.fillna(t.median())

# 2) stadium_type categorical
if "stadium_type" not in df.columns:
    roof = df.get("roof", "unknown").fillna("unknown").astype(str).str.lower()
    df["stadium_type"] = np.where(roof.eq("open"), "open", "domed")
df["stadium_type"] = df["stadium_type"].astype("category")

# 3) clutch fallback
if "clutch_kick" in df.columns:
    df["clutch_kick"] = pd.to_numeric(df["clutch_kick"], errors="coerce").fillna(0).astype(int)
else:
    df["clutch_kick"] = 0

# 4) poly terms (no I())
df["kd_sq"] = df["kick_distance"] ** 2

# 5) distance dummies (use rounded distance)
cuts = [20, 25, 30, 31, 32, 33, 34, 35, 36, 37, 38]
present_cuts = [c for c in cuts if (df["dist_yd"] == c).any()]

for c in present_cuts:
    df[f"D{c}"] = (df["dist_yd"] == c).astype(int)

# 6) formula
dummy_terms = " + ".join([f"D{c}" for c in present_cuts]) if present_cuts else "0"
ctrls = "kick_distance + kd_sq + wind_filled + temp_filled + stadium_type + clutch_kick"
formula = f"field_goal_result ~ {dummy_terms} + {ctrls}"

# 7) split samples
df_pre  = df[df["year"] < 2015].copy()
df_post = df[df["year"] >= 2015].copy()

def fit_cluster_or_hc1(d):
    m = smf.ols(formula, data=d)
    if "game_id" in d.columns and d["game_id"].notna().any():
        return m.fit(cov_type="cluster", cov_kwds={"groups": d["game_id"]})
    return m.fit(cov_type="HC1")

# 8) fit
model_pre  = fit_cluster_or_hc1(df_pre)
model_post = fit_cluster_or_hc1(df_post)

print("=== Pre-2015 ===")
print(model_pre.summary().tables[1])

print("\n=== 2015+ ===")
print(model_post.summary().tables[1])


# **KICKER TIERS (Rookie / Mid / Veteran by attempt share)**

df = df_field_goal.copy()

# 0) career attempts per kicker
df["career_attempts"] = (
    df.groupby("kicker_player_name", observed=True)["kicker_player_name"]
      .transform("size")
)

# 1) one row per kicker
kickers = (
    df[["kicker_player_name", "career_attempts"]]
      .drop_duplicates()
      .sort_values(["career_attempts", "kicker_player_name"])
      .reset_index(drop=True)
)

# 2) cumulative attempt share
kickers["cum_attempts"] = kickers["career_attempts"].cumsum()
kickers["cum_share"] = kickers["cum_attempts"] / kickers["career_attempts"].sum()

# 3) tiers (each ~1/3 of attempts)
def tier_from_share(s):
    if s <= 1/3:
        return "Rookie"
    elif s <= 2/3:
        return "Mid"
    return "Veteran"

kickers["quality"] = kickers["cum_share"].apply(tier_from_share).astype("category")

# 4) map back to attempts
tier_map = kickers.set_index("kicker_player_name")["quality"]
df_field_goal["quality"] = df_field_goal["kicker_player_name"].map(tier_map).astype("category")

print(df_field_goal["quality"].value_counts())

"""# **OLS: POLYNOMIAL + DISTANCE DUMMIES + CONTROLS (CLUSTERED)**"""

# **OLS: POLY + DISTANCE DUMMIES + CONTROLS (CLUSTERED)**
# running var = kick_distance (actual kick length)

df = df_field_goal.copy()

# 0) core types / drop missing essentials
df["field_goal_result"] = pd.to_numeric(df.get("field_goal_result"), errors="coerce")
df["kick_distance"]     = pd.to_numeric(df.get("kick_distance"), errors="coerce")
df = df.dropna(subset=["field_goal_result", "kick_distance"]).copy()

# 1) rounded distance for dummies
df["dist_yd"] = df["kick_distance"].round().astype(int)

# 2) wind/temp fills
if "wind_filled" not in df.columns:
    df["wind_filled"] = pd.to_numeric(df.get("wind"), errors="coerce").fillna(0)
else:
    df["wind_filled"] = pd.to_numeric(df["wind_filled"], errors="coerce").fillna(0)

if "temp_filled" not in df.columns:
    t = pd.to_numeric(df.get("temp"), errors="coerce")
    df["temp_filled"] = t.fillna(t.median())
else:
    t = pd.to_numeric(df["temp_filled"], errors="coerce")
    df["temp_filled"] = t.fillna(t.median())

# 3) stadium_type categorical
if "stadium_type" not in df.columns:
    roof = df.get("roof", "unknown").fillna("unknown").astype(str).str.lower()
    df["stadium_type"] = np.where(roof.eq("open"), "open", "domed")
df["stadium_type"] = df["stadium_type"].astype("category")

# 4) clutch fallback
if "clutch_kick" in df.columns:
    df["clutch_kick"] = pd.to_numeric(df["clutch_kick"], errors="coerce").fillna(0).astype(int)
else:
    df["clutch_kick"] = 0

# 5) kicker_experience (only if present)
if "kicker_experience" in df.columns:
    df["kicker_experience"] = pd.to_numeric(df["kicker_experience"], errors="coerce")

# 6) polynomial (no I())
df["kick_distance_sq"] = df["kick_distance"] ** 2

# 7) distance dummies (only those that exist)
cuts = [20, 25, 30, 31, 32, 33, 34, 35, 36, 37, 38]
present = [c for c in cuts if (df["dist_yd"] == c).any()]
for c in present:
    df[f"D{c}"] = (df["dist_yd"] == c).astype(int)

# 8) formula
poly    = "kick_distance + kick_distance_sq"
dummies = " + ".join([f"D{c}" for c in present]) if present else "0"

ctrl_list = ["wind_filled", "temp_filled", "stadium_type", "clutch_kick"]
if "kicker_experience" in df.columns and df["kicker_experience"].notna().any():
    ctrl_list.append("kicker_experience")
ctrls = " + ".join(ctrl_list)

formula = f"field_goal_result ~ {poly} + {dummies} + {ctrls}"

# 9) fit (cluster by game if possible)
if "game_id" in df.columns and df["game_id"].notna().any():
    res = smf.ols(formula, data=df).fit(cov_type="cluster", cov_kwds={"groups": df["game_id"]})
else:
    res = smf.ols(formula, data=df).fit(cov_type="HC1")

print(res.summary())


# **ONLY ROOKIES (same model, same running var = kick_distance)**

# 0) rookies only
req = ["quality", "kick_distance", "field_goal_result"]
miss = [c for c in req if c not in df_field_goal.columns]
if miss:
    raise KeyError(f"df_field_goal missing required columns: {miss}")

df = df_field_goal.loc[df_field_goal["quality"].astype(str).eq("Rookie")].copy()
if df.empty:
    raise ValueError("No rookie attempts (quality == 'Rookie').")

# 1) core types / drop essentials
df["field_goal_result"] = pd.to_numeric(df.get("field_goal_result"), errors="coerce")
df["kick_distance"]     = pd.to_numeric(df.get("kick_distance"), errors="coerce")
df = df.dropna(subset=["field_goal_result", "kick_distance"]).copy()

# 2) rounded distance for dummies
df["dist_yd"] = df["kick_distance"].round().astype(int)

# 3) wind/temp fills
if "wind_filled" not in df.columns:
    df["wind_filled"] = pd.to_numeric(df.get("wind"), errors="coerce").fillna(0)
else:
    df["wind_filled"] = pd.to_numeric(df["wind_filled"], errors="coerce").fillna(0)

if "temp_filled" not in df.columns:
    t = pd.to_numeric(df.get("temp"), errors="coerce")
    df["temp_filled"] = t.fillna(t.median())
else:
    t = pd.to_numeric(df["temp_filled"], errors="coerce")
    df["temp_filled"] = t.fillna(t.median())

# 4) stadium_type categorical
if "stadium_type" not in df.columns:
    roof = df.get("roof", "unknown").fillna("unknown").astype(str).str.lower()
    df["stadium_type"] = np.where(roof.eq("open"), "open", "domed")
df["stadium_type"] = df["stadium_type"].astype("category")

# 5) clutch fallback
if "clutch_kick" in df.columns:
    df["clutch_kick"] = pd.to_numeric(df["clutch_kick"], errors="coerce").fillna(0).astype(int)
else:
    df["clutch_kick"] = 0

# 6) kicker_experience (only if present)
if "kicker_experience" in df.columns:
    df["kicker_experience"] = pd.to_numeric(df["kicker_experience"], errors="coerce")

# 7) polynomial
df["kick_distance_sq"] = df["kick_distance"] ** 2

# 8) dummies (rookie-present only)
cuts = [20, 25, 30, 31, 32, 33, 34, 35, 36, 37, 38]
present = [c for c in cuts if (df["dist_yd"] == c).any()]
for c in present:
    df[f"D{c}"] = (df["dist_yd"] == c).astype(int)

# 9) formula
poly    = "kick_distance + kick_distance_sq"
dummies = " + ".join([f"D{c}" for c in present]) if present else "0"

ctrl_list = ["wind_filled", "temp_filled", "stadium_type", "clutch_kick"]
if "kicker_experience" in df.columns and df["kicker_experience"].notna().any():
    ctrl_list.append("kicker_experience")
ctrls = " + ".join(ctrl_list)

formula = f"field_goal_result ~ {poly} + {dummies} + {ctrls}"

# 10) fit (cluster by game if possible)
if "game_id" in df.columns and df["game_id"].notna().any():
    res_r = smf.ols(formula, data=df).fit(cov_type="cluster", cov_kwds={"groups": df["game_id"]})
else:
    res_r = smf.ols(formula, data=df).fit(cov_type="HC1")

ng = df["game_id"].nunique() if "game_id" in df.columns else "N/A"
print(f"Rookie attempts: {len(df)} | games: {ng} | distance dummies: {present}")
print(res_r.summary())


# **ONLY ROOKIES (time-varying dummy effects, same style as above)**

df = df_field_goal.loc[df_field_goal["quality"].astype(str).eq("Rookie")].copy()
if df.empty:
    raise ValueError("No rookie attempts (quality == 'Rookie').")

# 0) season for centering
if "season" not in df.columns and "year" in df.columns:
    df["season"] = pd.to_numeric(df["year"], errors="coerce")
else:
    df["season"] = pd.to_numeric(df.get("season"), errors="coerce")

# 1) core types / drop essentials
df["field_goal_result"] = pd.to_numeric(df.get("field_goal_result"), errors="coerce")
df["kick_distance"]     = pd.to_numeric(df.get("kick_distance"), errors="coerce")
df = df.dropna(subset=["field_goal_result", "kick_distance", "season"]).copy()

# 2) rounded distance and centered year
df["dist_yd"] = df["kick_distance"].round().astype(int)
df["yr_c"] = df["season"] - df["season"].mean()

# 3) wind/temp fills
if "wind_filled" not in df.columns:
    df["wind_filled"] = pd.to_numeric(df.get("wind"), errors="coerce").fillna(0)
else:
    df["wind_filled"] = pd.to_numeric(df["wind_filled"], errors="coerce").fillna(0)

if "temp_filled" not in df.columns:
    t = pd.to_numeric(df.get("temp"), errors="coerce")
    df["temp_filled"] = t.fillna(t.median())
else:
    t = pd.to_numeric(df["temp_filled"], errors="coerce")
    df["temp_filled"] = t.fillna(t.median())

# 4) stadium_type categorical
if "stadium_type" not in df.columns:
    roof = df.get("roof", "unknown").fillna("unknown").astype(str).str.lower()
    df["stadium_type"] = np.where(roof.eq("open"), "open", "domed")
df["stadium_type"] = df["stadium_type"].astype("category")

# 5) clutch fallback
if "clutch_kick" in df.columns:
    df["clutch_kick"] = pd.to_numeric(df["clutch_kick"], errors="coerce").fillna(0).astype(int)
else:
    df["clutch_kick"] = 0

# 6) kicker_experience optional
if "kicker_experience" in df.columns:
    df["kicker_experience"] = pd.to_numeric(df["kicker_experience"], errors="coerce")

# 7) poly
df["kick_distance_sq"] = df["kick_distance"] ** 2

# 8) dummies + interactions
cuts = [25, 30, 33, 34, 35, 36, 37, 38]
present = [c for c in cuts if (df["dist_yd"] == c).any()]
for c in present:
    df[f"D{c}"] = (df["dist_yd"] == c).astype(int)
    df[f"D{c}_yr"] = df[f"D{c}"] * df["yr_c"]

# 9) formula
poly = "kick_distance + kick_distance_sq"
dummies   = " + ".join([f"D{c}" for c in present]) if present else "0"
interacts = " + ".join([f"D{c}_yr" for c in present]) if present else "0"

ctrl_list = ["wind_filled", "temp_filled", "stadium_type", "clutch_kick"]
if "kicker_experience" in df.columns and df["kicker_experience"].notna().any():
    ctrl_list.append("kicker_experience")
ctrls = " + ".join(ctrl_list)

formula = f"field_goal_result ~ {poly} + {dummies} + {interacts} + {ctrls}"

# 10) fit
if "game_id" in df.columns and df["game_id"].notna().any():
    res_tv = smf.ols(formula, data=df).fit(cov_type="cluster", cov_kwds={"groups": df["game_id"]})
else:
    res_tv = smf.ols(formula, data=df).fit(cov_type="HC1")

print(res_tv.summary())

wanted = [k for k in res_tv.params.index if k.startswith("D")]
print("\nDistance dummy + interaction coefs:")
print(res_tv.params.loc[wanted].to_string())
print("\nStd errors:")
print(res_tv.bse.loc[wanted].to_string())

"""# **SEASON FIXED EFFECTS**"""

# **SEASON FIXED EFFECTS**
# for success models: running var = kick_distance (actual kick length)
# season FE just soaks up year-to-year shifts

df = df_field_goal.copy()

# 0) season as category
if "season" not in df.columns and "year" in df.columns:
    df["season"] = pd.to_numeric(df["year"], errors="coerce")
else:
    df["season"] = pd.to_numeric(df.get("season"), errors="coerce")
df["season"] = df["season"].astype("Int64").astype("category")

# 1) core numerics
df["field_goal_result"] = pd.to_numeric(df.get("field_goal_result"), errors="coerce")
df["kick_distance"]     = pd.to_numeric(df.get("kick_distance"), errors="coerce")

# 2) wind/temp fills
if "wind_filled" not in df.columns:
    df["wind_filled"] = pd.to_numeric(df.get("wind"), errors="coerce").fillna(0)
else:
    df["wind_filled"] = pd.to_numeric(df["wind_filled"], errors="coerce").fillna(0)

if "temp_filled" not in df.columns:
    t = pd.to_numeric(df.get("temp"), errors="coerce")
    df["temp_filled"] = t.fillna(t.median())
else:
    t = pd.to_numeric(df["temp_filled"], errors="coerce")
    df["temp_filled"] = t.fillna(t.median())

# 3) stadium_type categorical
if "stadium_type" not in df.columns:
    roof = df.get("roof", "unknown").fillna("unknown").astype(str).str.lower()
    df["stadium_type"] = np.where(roof.eq("open"), "open", "domed")
df["stadium_type"] = df["stadium_type"].astype("category")

# 4) clutch fallback
if "clutch_kick" in df.columns:
    df["clutch_kick"] = pd.to_numeric(df["clutch_kick"], errors="coerce").fillna(0).astype(int)
else:
    if ("game_seconds_remaining" in df.columns) and ("qtr" in df.columns):
        gsr = pd.to_numeric(df["game_seconds_remaining"], errors="coerce")
        qtr = pd.to_numeric(df["qtr"], errors="coerce")
        df["clutch_kick"] = ((gsr <= 120) | (qtr >= 5)).fillna(False).astype(int)
    else:
        df["clutch_kick"] = 0

# 5) kicker_experience optional
if "kicker_experience" in df.columns:
    df["kicker_experience"] = pd.to_numeric(df["kicker_experience"], errors="coerce")

# 6) drop essentials
need = ["field_goal_result", "kick_distance", "season"]
df = df.dropna(subset=need).copy()
if df.empty:
    raise ValueError("No rows left after cleaning essentials.")

# 7) poly + distance dummies (on rounded kick_distance)
df["kick_distance_sq"] = df["kick_distance"] ** 2
df["dist_yd"] = df["kick_distance"].round().astype(int)

cuts = [20, 25, 30, 31, 32, 33, 34, 35, 36, 37, 38]
present = [c for c in cuts if (df["dist_yd"] == c).any()]
for c in present:
    df[f"D{c}"] = (df["dist_yd"] == c).astype(int)

# 8) controls list (drop stadium_type if it collapses)
ctrl_list = ["wind_filled", "temp_filled", "stadium_type", "clutch_kick"]
if "kicker_experience" in df.columns and df["kicker_experience"].notna().any():
    ctrl_list.append("kicker_experience")

if "stadium_type" in ctrl_list and df["stadium_type"].nunique(dropna=True) <= 1:
    ctrl_list.remove("stadium_type")

# 9) formula (season FE by including categorical season)
poly    = "kick_distance + kick_distance_sq"
dummies = " + ".join([f"D{c}" for c in present]) if present else "0"
ctrls   = " + ".join(ctrl_list) if ctrl_list else "1"
formula_fe = f"field_goal_result ~ {poly} + {dummies} + {ctrls} + season"

# 10) fit clustered
if "game_id" in df.columns and df["game_id"].notna().any():
    res_fe = smf.ols(formula_fe, data=df).fit(cov_type="cluster", cov_kwds={"groups": df["game_id"]})
else:
    res_fe = smf.ols(formula_fe, data=df).fit(cov_type="HC1")

print(res_fe.summary().tables[1])


# **ONLY ROOKIES (same exact spec)**

df = df_field_goal.loc[df_field_goal["quality"].astype(str).eq("Rookie")].copy()
if df.empty:
    raise ValueError("No rookie attempts (quality == 'Rookie').")

# 0) season as category
if "season" not in df.columns and "year" in df.columns:
    df["season"] = pd.to_numeric(df["year"], errors="coerce")
else:
    df["season"] = pd.to_numeric(df.get("season"), errors="coerce")
df["season"] = df["season"].astype("Int64").astype("category")

# 1) core numerics
df["field_goal_result"] = pd.to_numeric(df.get("field_goal_result"), errors="coerce")
df["kick_distance"]     = pd.to_numeric(df.get("kick_distance"), errors="coerce")

# 2) wind/temp fills
if "wind_filled" not in df.columns:
    df["wind_filled"] = pd.to_numeric(df.get("wind"), errors="coerce").fillna(0)
else:
    df["wind_filled"] = pd.to_numeric(df["wind_filled"], errors="coerce").fillna(0)

if "temp_filled" not in df.columns:
    t = pd.to_numeric(df.get("temp"), errors="coerce")
    df["temp_filled"] = t.fillna(t.median())
else:
    t = pd.to_numeric(df["temp_filled"], errors="coerce")
    df["temp_filled"] = t.fillna(t.median())

# 3) stadium_type categorical
if "stadium_type" not in df.columns:
    roof = df.get("roof", "unknown").fillna("unknown").astype(str).str.lower()
    df["stadium_type"] = np.where(roof.eq("open"), "open", "domed")
df["stadium_type"] = df["stadium_type"].astype("category")

# 4) clutch fallback
if "clutch_kick" in df.columns:
    df["clutch_kick"] = pd.to_numeric(df["clutch_kick"], errors="coerce").fillna(0).astype(int)
else:
    if ("game_seconds_remaining" in df.columns) and ("qtr" in df.columns):
        gsr = pd.to_numeric(df["game_seconds_remaining"], errors="coerce")
        qtr = pd.to_numeric(df["qtr"], errors="coerce")
        df["clutch_kick"] = ((gsr <= 120) | (qtr >= 5)).fillna(False).astype(int)
    else:
        df["clutch_kick"] = 0

# 5) kicker_experience optional
if "kicker_experience" in df.columns:
    df["kicker_experience"] = pd.to_numeric(df["kicker_experience"], errors="coerce")

# 6) drop essentials
need = ["field_goal_result", "kick_distance", "season"]
df = df.dropna(subset=need).copy()
if df.empty:
    raise ValueError("No rookie rows left after cleaning essentials.")

# 7) poly + distance dummies
df["kick_distance_sq"] = df["kick_distance"] ** 2
df["dist_yd"] = df["kick_distance"].round().astype(int)

cuts = [20, 25, 30, 31, 32, 33, 34, 35, 36, 37, 38]
present = [c for c in cuts if (df["dist_yd"] == c).any()]
for c in present:
    df[f"D{c}"] = (df["dist_yd"] == c).astype(int)

# 8) controls list (drop stadium_type if degenerate among rookies)
ctrl_list = ["wind_filled", "temp_filled", "stadium_type", "clutch_kick"]
if "kicker_experience" in df.columns and df["kicker_experience"].notna().any():
    ctrl_list.append("kicker_experience")

if "stadium_type" in ctrl_list and df["stadium_type"].nunique(dropna=True) <= 1:
    ctrl_list.remove("stadium_type")

# 9) formula
poly    = "kick_distance + kick_distance_sq"
dummies = " + ".join([f"D{c}" for c in present]) if present else "0"
ctrls   = " + ".join(ctrl_list) if ctrl_list else "1"
formula_fe = f"field_goal_result ~ {poly} + {dummies} + {ctrls} + season"

# 10) fit
if "game_id" in df.columns and df["game_id"].notna().any():
    res_r_fe = smf.ols(formula_fe, data=df).fit(cov_type="cluster", cov_kwds={"groups": df["game_id"]})
else:
    res_r_fe = smf.ols(formula_fe, data=df).fit(cov_type="HC1")

ng = df["game_id"].nunique() if "game_id" in df.columns else "N/A"
print(f"Rookie attempts: {len(df)} | seasons: {df['season'].nunique()} | dummies: {present} | games: {ng}")
print(res_r_fe.summary().tables[1])

"""# **TIME-VARYING DISTANCE SLOPES**"""

# **TIME-VARYING DISTANCE SLOPES**
# success model: running var = kick_distance (actual kick length)
# let the slope on distance change over time (distance × yr_c)

df = df_field_goal.copy()

# 0) season int + centered
if "season" not in df.columns and "year" in df.columns:
    df["season"] = pd.to_numeric(df["year"], errors="coerce")
else:
    df["season"] = pd.to_numeric(df.get("season"), errors="coerce")
df = df.dropna(subset=["season"]).copy()
df["season"] = df["season"].astype(int)
df["yr_c"] = df["season"] - df["season"].mean()

# 1) core numerics
df["field_goal_result"] = pd.to_numeric(df.get("field_goal_result"), errors="coerce")
df["kick_distance"]     = pd.to_numeric(df.get("kick_distance"), errors="coerce")
df = df.dropna(subset=["field_goal_result", "kick_distance"]).copy()

df["kick_distance_sq"] = df["kick_distance"] ** 2
df["dist_yd"] = df["kick_distance"].round().astype(int)

# 2) wind/temp fills
if "wind_filled" not in df.columns:
    df["wind_filled"] = pd.to_numeric(df.get("wind"), errors="coerce").fillna(0)
else:
    df["wind_filled"] = pd.to_numeric(df["wind_filled"], errors="coerce").fillna(0)

if "temp_filled" not in df.columns:
    t = pd.to_numeric(df.get("temp"), errors="coerce")
    df["temp_filled"] = t.fillna(t.median())
else:
    t = pd.to_numeric(df["temp_filled"], errors="coerce")
    df["temp_filled"] = t.fillna(t.median())

# 3) stadium_type categorical
if "stadium_type" not in df.columns:
    roof = df.get("roof", "unknown").fillna("unknown").astype(str).str.lower()
    df["stadium_type"] = np.where(roof.eq("open"), "open", "domed")
df["stadium_type"] = df["stadium_type"].astype("category")

# 4) clutch fallback
if "clutch_kick" in df.columns:
    df["clutch_kick"] = pd.to_numeric(df["clutch_kick"], errors="coerce").fillna(0).astype(int)
else:
    if ("game_seconds_remaining" in df.columns) and ("qtr" in df.columns):
        gsr = pd.to_numeric(df["game_seconds_remaining"], errors="coerce")
        qtr = pd.to_numeric(df["qtr"], errors="coerce")
        df["clutch_kick"] = ((gsr <= 120) | (qtr >= 5)).fillna(False).astype(int)
    else:
        df["clutch_kick"] = 0

# 5) kicker_experience optional
if "kicker_experience" in df.columns:
    df["kicker_experience"] = pd.to_numeric(df["kicker_experience"], errors="coerce")

# 6) distance dummies (only where they exist)
cuts = [20, 25, 30, 31, 32, 33, 34, 35, 36, 37, 38]
present = [c for c in cuts if (df["dist_yd"] == c).any()]
for c in present:
    df[f"D{c}"] = (df["dist_yd"] == c).astype(int)

dummies = " + ".join([f"D{c}" for c in present]) if present else "0"

# 7) controls (drop stadium_type if it collapses)
ctrl_list = ["wind_filled", "temp_filled", "stadium_type", "clutch_kick"]
if "kicker_experience" in df.columns and df["kicker_experience"].notna().any():
    ctrl_list.append("kicker_experience")

if "stadium_type" in ctrl_list and df["stadium_type"].nunique(dropna=True) <= 1:
    ctrl_list.remove("stadium_type")

controls = " + ".join(ctrl_list) if ctrl_list else "1"

# 8) time-varying slope formula (distance × yr_c)
formula_tvs = (
    "field_goal_result ~ "
    "kick_distance * yr_c + "
    "kick_distance_sq * yr_c + "
    f"{dummies} + {controls}"
)

# 9) fit clustered by game
if "game_id" in df.columns and df["game_id"].notna().any():
    res_tvs = smf.ols(formula_tvs, data=df).fit(
        cov_type="cluster",
        cov_kwds={"groups": df["game_id"]}
    )
else:
    res_tvs = smf.ols(formula_tvs, data=df).fit(cov_type="HC1")

print(res_tvs.summary().tables[1])


# **ONLY ROOKIES (same exact spec)**

df = df_field_goal.loc[df_field_goal["quality"].astype(str).eq("Rookie")].copy()
if df.empty:
    raise ValueError("No rookie attempts (quality == 'Rookie').")

# 0) season int + centered
if "season" not in df.columns and "year" in df.columns:
    df["season"] = pd.to_numeric(df["year"], errors="coerce")
else:
    df["season"] = pd.to_numeric(df.get("season"), errors="coerce")
df = df.dropna(subset=["season"]).copy()
df["season"] = df["season"].astype(int)
df["yr_c"] = df["season"] - df["season"].mean()

# 1) core numerics
df["field_goal_result"] = pd.to_numeric(df.get("field_goal_result"), errors="coerce")
df["kick_distance"]     = pd.to_numeric(df.get("kick_distance"), errors="coerce")
df = df.dropna(subset=["field_goal_result", "kick_distance"]).copy()

df["kick_distance_sq"] = df["kick_distance"] ** 2
df["dist_yd"] = df["kick_distance"].round().astype(int)

# 2) wind/temp fills
if "wind_filled" not in df.columns:
    df["wind_filled"] = pd.to_numeric(df.get("wind"), errors="coerce").fillna(0)
else:
    df["wind_filled"] = pd.to_numeric(df["wind_filled"], errors="coerce").fillna(0)

if "temp_filled" not in df.columns:
    t = pd.to_numeric(df.get("temp"), errors="coerce")
    df["temp_filled"] = t.fillna(t.median())
else:
    t = pd.to_numeric(df["temp_filled"], errors="coerce")
    df["temp_filled"] = t.fillna(t.median())

# 3) stadium_type categorical
if "stadium_type" not in df.columns:
    roof = df.get("roof", "unknown").fillna("unknown").astype(str).str.lower()
    df["stadium_type"] = np.where(roof.eq("open"), "open", "domed")
df["stadium_type"] = df["stadium_type"].astype("category")

# 4) clutch fallback
if "clutch_kick" in df.columns:
    df["clutch_kick"] = pd.to_numeric(df["clutch_kick"], errors="coerce").fillna(0).astype(int)
else:
    if ("game_seconds_remaining" in df.columns) and ("qtr" in df.columns):
        gsr = pd.to_numeric(df["game_seconds_remaining"], errors="coerce")
        qtr = pd.to_numeric(df["qtr"], errors="coerce")
        df["clutch_kick"] = ((gsr <= 120) | (qtr >= 5)).fillna(False).astype(int)
    else:
        df["clutch_kick"] = 0

# 5) kicker_experience optional
if "kicker_experience" in df.columns:
    df["kicker_experience"] = pd.to_numeric(df["kicker_experience"], errors="coerce")

# 6) distance dummies
cuts = [20, 25, 30, 31, 32, 33, 34, 35, 36, 37, 38]
present = [c for c in cuts if (df["dist_yd"] == c).any()]
for c in present:
    df[f"D{c}"] = (df["dist_yd"] == c).astype(int)

dummies = " + ".join([f"D{c}" for c in present]) if present else "0"

# 7) controls (drop stadium_type if degenerate among rookies)
ctrl_list = ["wind_filled", "temp_filled", "stadium_type", "clutch_kick"]
if "kicker_experience" in df.columns and df["kicker_experience"].notna().any():
    ctrl_list.append("kicker_experience")

if "stadium_type" in ctrl_list and df["stadium_type"].nunique(dropna=True) <= 1:
    ctrl_list.remove("stadium_type")

controls = " + ".join(ctrl_list) if ctrl_list else "1"

# 8) formula
formula_tvs = (
    "field_goal_result ~ "
    "kick_distance * yr_c + "
    "kick_distance_sq * yr_c + "
    f"{dummies} + {controls}"
)

# 9) fit
if "game_id" in df.columns and df["game_id"].notna().any():
    res_tvs_r = smf.ols(formula_tvs, data=df).fit(
        cov_type="cluster",
        cov_kwds={"groups": df["game_id"]}
    )
else:
    res_tvs_r = smf.ols(formula_tvs, data=df).fit(cov_type="HC1")

ng = df["game_id"].nunique() if "game_id" in df.columns else "N/A"
print(f"Rookie attempts: {len(df)} | games: {ng} | dummies: {present}")
print(res_tvs_r.summary().tables[1])

"""# **Grouped-season fixed effects**"""

# **GROUPED-SEASON FIXED EFFECTS**
# success model: running var = kick_distance (actual kick length)
# grouped season FE via yr_bin

df = df_field_goal.copy()

# 0) season -> numeric
if "season" not in df.columns and "year" in df.columns:
    df["season"] = pd.to_numeric(df["year"], errors="coerce")
else:
    df["season"] = pd.to_numeric(df.get("season"), errors="coerce")
df = df.dropna(subset=["season"]).copy()
df["season"] = df["season"].astype(int)

# 1) yr_bin bins
bins   = [1999, 2005, 2010, 2015, 2019, 2026]
labels = ["1999–2004", "2005–2009", "2010–2014", "2015–2019", "2020–2025"]

df["yr_bin"] = pd.cut(
    df["season"],
    bins=bins,
    labels=labels,
    right=False,
    include_lowest=True
).astype("category")

# 2) core numerics
df["field_goal_result"] = pd.to_numeric(df.get("field_goal_result"), errors="coerce")
df["kick_distance"]     = pd.to_numeric(df.get("kick_distance"), errors="coerce")
df = df.dropna(subset=["field_goal_result", "kick_distance", "yr_bin"]).copy()

df["kick_distance_sq"] = df["kick_distance"] ** 2
df["dist_yd"] = df["kick_distance"].round().astype(int)

# 3) wind/temp fills
if "wind_filled" not in df.columns:
    df["wind_filled"] = pd.to_numeric(df.get("wind"), errors="coerce").fillna(0)
else:
    df["wind_filled"] = pd.to_numeric(df["wind_filled"], errors="coerce").fillna(0)

if "temp_filled" not in df.columns:
    t = pd.to_numeric(df.get("temp"), errors="coerce")
    df["temp_filled"] = t.fillna(t.median())
else:
    t = pd.to_numeric(df["temp_filled"], errors="coerce")
    df["temp_filled"] = t.fillna(t.median())

# 4) stadium_type categorical
if "stadium_type" not in df.columns:
    roof = df.get("roof", "unknown").fillna("unknown").astype(str).str.lower()
    df["stadium_type"] = np.where(roof.eq("open"), "open", "domed")
df["stadium_type"] = df["stadium_type"].astype("category")

# 5) clutch fallback
if "clutch_kick" in df.columns:
    df["clutch_kick"] = pd.to_numeric(df["clutch_kick"], errors="coerce").fillna(0).astype(int)
else:
    if ("game_seconds_remaining" in df.columns) and ("qtr" in df.columns):
        gsr = pd.to_numeric(df["game_seconds_remaining"], errors="coerce")
        qtr = pd.to_numeric(df["qtr"], errors="coerce")
        df["clutch_kick"] = ((gsr <= 120) | (qtr >= 5)).fillna(False).astype(int)
    else:
        df["clutch_kick"] = 0

# 6) kicker_experience optional
if "kicker_experience" in df.columns:
    df["kicker_experience"] = pd.to_numeric(df["kicker_experience"], errors="coerce")

# 7) distance dummies (only those that exist)
cuts = [20, 25, 30, 31, 32, 33, 34, 35, 36, 37, 38]
present = [c for c in cuts if (df["dist_yd"] == c).any()]
for c in present:
    df[f"D{c}"] = (df["dist_yd"] == c).astype(int)

dummies = " + ".join([f"D{c}" for c in present]) if present else "0"

# 8) controls (drop stadium_type if degenerate)
ctrl_list = ["wind_filled", "temp_filled", "stadium_type", "clutch_kick"]
if "kicker_experience" in df.columns and df["kicker_experience"].notna().any():
    ctrl_list.append("kicker_experience")

if "stadium_type" in ctrl_list and df["stadium_type"].nunique(dropna=True) <= 1:
    ctrl_list.remove("stadium_type")

controls = " + ".join(ctrl_list) if ctrl_list else "1"

# 9) formula
formula_bin = f"field_goal_result ~ kick_distance + kick_distance_sq + {dummies} + {controls} + yr_bin"

# 10) fit clustered by game
if "game_id" in df.columns and df["game_id"].notna().any():
    res_bin = smf.ols(formula_bin, data=df).fit(
        cov_type="cluster",
        cov_kwds={"groups": df["game_id"]}
    )
else:
    res_bin = smf.ols(formula_bin, data=df).fit(cov_type="HC1")

print(res_bin.summary().tables[1])


# **ONLY ROOKIES (same exact spec)**

df = df_field_goal.loc[df_field_goal["quality"].astype(str).eq("Rookie")].copy()
if df.empty:
    raise ValueError("No rookie attempts (quality == 'Rookie').")

# 0) season -> numeric
if "season" not in df.columns and "year" in df.columns:
    df["season"] = pd.to_numeric(df["year"], errors="coerce")
else:
    df["season"] = pd.to_numeric(df.get("season"), errors="coerce")
df = df.dropna(subset=["season"]).copy()
df["season"] = df["season"].astype(int)

# 1) yr_bin bins
bins   = [1999, 2005, 2010, 2015, 2019, 2026]
labels = ["1999–2004", "2005–2009", "2010–2014", "2015–2019", "2020–2025"]

df["yr_bin"] = pd.cut(
    df["season"],
    bins=bins,
    labels=labels,
    right=False,
    include_lowest=True
).astype("category")

# 2) core numerics
df["field_goal_result"] = pd.to_numeric(df.get("field_goal_result"), errors="coerce")
df["kick_distance"]     = pd.to_numeric(df.get("kick_distance"), errors="coerce")
df = df.dropna(subset=["field_goal_result", "kick_distance", "yr_bin"]).copy()

df["kick_distance_sq"] = df["kick_distance"] ** 2
df["dist_yd"] = df["kick_distance"].round().astype(int)

# 3) wind/temp fills
if "wind_filled" not in df.columns:
    df["wind_filled"] = pd.to_numeric(df.get("wind"), errors="coerce").fillna(0)
else:
    df["wind_filled"] = pd.to_numeric(df["wind_filled"], errors="coerce").fillna(0)

if "temp_filled" not in df.columns:
    t = pd.to_numeric(df.get("temp"), errors="coerce")
    df["temp_filled"] = t.fillna(t.median())
else:
    t = pd.to_numeric(df["temp_filled"], errors="coerce")
    df["temp_filled"] = t.fillna(t.median())

# 4) stadium_type categorical
if "stadium_type" not in df.columns:
    roof = df.get("roof", "unknown").fillna("unknown").astype(str).str.lower()
    df["stadium_type"] = np.where(roof.eq("open"), "open", "domed")
df["stadium_type"] = df["stadium_type"].astype("category")

# 5) clutch fallback
if "clutch_kick" in df.columns:
    df["clutch_kick"] = pd.to_numeric(df["clutch_kick"], errors="coerce").fillna(0).astype(int)
else:
    if ("game_seconds_remaining" in df.columns) and ("qtr" in df.columns):
        gsr = pd.to_numeric(df["game_seconds_remaining"], errors="coerce")
        qtr = pd.to_numeric(df["qtr"], errors="coerce")
        df["clutch_kick"] = ((gsr <= 120) | (qtr >= 5)).fillna(False).astype(int)
    else:
        df["clutch_kick"] = 0

# 6) kicker_experience optional
if "kicker_experience" in df.columns:
    df["kicker_experience"] = pd.to_numeric(df["kicker_experience"], errors="coerce")

# 7) distance dummies
cuts = [20, 25, 30, 31, 32, 33, 34, 35, 36, 37, 38]
present = [c for c in cuts if (df["dist_yd"] == c).any()]
for c in present:
    df[f"D{c}"] = (df["dist_yd"] == c).astype(int)

dummies = " + ".join([f"D{c}" for c in present]) if present else "0"

# 8) controls (drop stadium_type if degenerate among rookies)
ctrl_list = ["wind_filled", "temp_filled", "stadium_type", "clutch_kick"]
if "kicker_experience" in df.columns and df["kicker_experience"].notna().any():
    ctrl_list.append("kicker_experience")

if "stadium_type" in ctrl_list and df["stadium_type"].nunique(dropna=True) <= 1:
    ctrl_list.remove("stadium_type")

controls = " + ".join(ctrl_list) if ctrl_list else "1"

# 9) formula
formula_bin = f"field_goal_result ~ kick_distance + kick_distance_sq + {dummies} + {controls} + yr_bin"

# 10) fit
if "game_id" in df.columns and df["game_id"].notna().any():
    res_bin_r = smf.ols(formula_bin, data=df).fit(
        cov_type="cluster",
        cov_kwds={"groups": df["game_id"]}
    )
else:
    res_bin_r = smf.ols(formula_bin, data=df).fit(cov_type="HC1")

ng = df["game_id"].nunique() if "game_id" in df.columns else "N/A"
print(f"Rookie attempts: {len(df)} | games: {ng}")
print(df["yr_bin"].value_counts().sort_index())
print(f"Dummies: {present}")
print(res_bin_r.summary().tables[1])